##Population Projections

```{r}
head(popgrowth)
```
#make subsets for each growth rate scenario
```{r}
LG <- filter(popgrowth, scenario == "LG")
```
```{r}
M1 <- filter(popgrowth, scenario == "M1")
```
```{r}
M2 <- filter(popgrowth, scenario == "M2")
```
```{r}
M3 <- filter(popgrowth, scenario == "M3")
```
```{r}
M4 <- filter(popgrowth, scenario == "M4")
```
```{r}
M5 <- filter(popgrowth, scenario == "M5")
```
```{r}
HG <- filter(popgrowth, scenario == "HG")
```
```{r}
SA <- filter(popgrowth, scenario == "SA")
```
```{r}
FA <- filter(popgrowth, scenario == "FA")
```

#mock figure 5.2/5.3
```{r}
popgrowth$fscenario <- factor(popgrowth$scenario)
```
```{r}
poplme <- lme(growthrate ~ year, random = ~1|fscenario,
    data = popgrowth)
```
```{r}
summary(poplme)
```
```{r}
f0 <- fitted(poplme, level = 0)
```
```{r}
f1 <- fitted(poplme, level = 1)
```
```{r}
I <- order(popgrowth$year); yearS <- sort(popgrowth$year)
```
```{r}
plot(yearS, f0[I], lwd = 2, type = "l",
     ylim = c(0, 15), ylab = "growth rate (people per thousand)", xlab = "year")
```
```{r}
for(i in 1:9){
  x1 <- popgrowth$year[popgrowth$scenario == i]
  y1 <- f1[popgrowth$scenario == i]
  K <- order(x1)
  lines(sort(x1), y1[K])}
```
```{r}
text(popgrowth$year, popgrowth$growthrate, popgrowth$scenario, cex = 0.7)
```
why that error?? plot.new has been called i think?!

```{r}
plot(yearS, f0[I], lwd = 2, type = "l",
     ylim = c(0, 15), ylab = "growth rate (people per thousand)", xlab = "year")
for(i in 1:9){
  x1 <- popgrowth$year[popgrowth$scenario == i]
  y1 <- f1[popgrowth$scenario == i]
  K <- order(x1)
  lines(sort(x1), y1[K])}
text(popgrowth$year, popgrowth$growthrate, popgrowth$scenario, cex = 0.7)
```
hm. ok. works like that. where's my lines tho.

try something else real quick: can i apply lme() to each growth rate scenario and add all those lines to one plot?
```{r}
LGlme <- lme(growthrate ~ year, random = ~1|fscenario,
    data = LG)
```
```{r}
M1lme <- lme(growthrate ~ year, random = ~1|fscenario,
    data = M1)
```
```{r}
M2lme <- lme(growthrate ~ year, random = ~1|fscenario,
    data = M2)
```
```{r}
M3lme <- lme(growthrate ~ year, random = ~1|fscenario,
    data = M3)
```
```{r}
M4lme <- lme(growthrate ~ year, random = ~1|fscenario,
    data = M4)
```
```{r}
M5lme <- lme(growthrate ~ year, random = ~1|fscenario,
    data = M5)
```
```{r}
HGlme <- lme(growthrate ~ year, random = ~1|fscenario,
    data = HG)
```
```{r}
SAlme <- lme(growthrate ~ year, random = ~1|fscenario,
    data = SA)
```
```{r}
FAlme <- lme(growthrate ~ year, random = ~1|fscenario,
    data = FA)
```

#slap it all on one graph
```{r}
plot(yearS, f0[I], lwd = 3, type = "l",
     ylim = c(0, 15), ylab = "growth rate (people per thousand)", xlab = "year") #gives the red dots
abline(LGlme) #lme lines for each scenario
abline(M1lme)
abline(M2lme)
abline(M3lme)
abline(M4lme)
abline(M5lme)
abline(HGlme)
abline(SAlme)
abline(FAlme)
```

