##time to play with data woohoo

```{r}
ok2019_2022 <- na.omit(ok1922NA) #get rid of NA values & rename the dataset
```

```{r}
fintry <- filter(ok2019_2022, park == "fintry") #make subsets for each park
```
```{r}
skaha <- filter(ok2019_2022, park == "skaha")
```
```{r}
manning <- filter(ok2019_2022, park == "manning")
```

##make some quick plots just for kicks!
#corrected attendance & avg temperature
```{r}
plot(fintry$avgtemp, fintry$visitorcorrected, 
     main = "fintry attendance vs temp",
     xlab = "avg temp (ºC)",
     ylab = "attendance (people per 1000)")
abline(lm(visitorcorrected ~ avgtemp, data = fintry))
```
```{r}
plot(skaha$avgtemp, skaha$visitorcorrected, 
     main = "skaha attendance vs temp",
     xlab = "avg temp (ºC)",
     ylab = "attendance (people per 1000)")
abline(lm(visitorcorrected ~ avgtemp, data = skaha))
```
```{r}
plot(manning$avgtemp, manning$visitorcorrected, 
     main = "manning attendance vs temp",
     xlab = "avg temp (ºC)",
     ylab = "attendance (people per 1000)") 
abline(lm(visitorcorrected ~ avgtemp, data = manning))
```

#corrected attendance & precipitation
```{r}
plot(fintry$avgprecip, fintry$visitorcorrected, 
     main = "fintry attendance vs precipitation",
     xlab = "avg precip (mm)",
     ylab = "attendance (people per 1000)")
abline(lm(visitorcorrected ~ avgprecip, data = fintry))
```
```{r}
plot(skaha$avgprecip, skaha$visitorcorrected, 
     main = "skaha attendance vs precipitation",
     xlab = "avg precip (mm)",
     ylab = "attendance (people per 1000)")
abline(lm(visitorcorrected ~ avgprecip, data = skaha))
```
```{r}
plot(manning$avgprecip, manning$visitorcorrected, 
     main = "manning attendance vs precipitation",
     xlab = "avg precip (mm)",
     ylab = "attendance (people per 1000)")
abline(lm(visitorcorrected ~ avgprecip, data = manning))
```